name: Update Post Title

on:
  schedule:
    - cron: '*/60 * * * *'
  workflow_dispatch:

jobs:
  update-post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests beautifulsoup4 gspread urllib3 oauth2client

      # Thay đổi lệnh này để tạo file credentials.json từ secret
      - name: Create Google Sheets Credentials File
        run: echo "${{ secrets.GOOGLE_CREDENTIALS }}" > credentials.json # Bỏ '| base64 --decode'

      - name: Run Update Post Title
        run: python postmkcom.py
