name: Update Post Title

on:
  schedule:
    - cron: '0 1-10 * * 1-6'
  workflow_dispatch:

jobs:
  update-post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests beautifulsoup4 gspread gspread-formatting urllib3 oauth2client

      # Giải mã credentials.json từ GitHub Secrets (bạn phải lưu file này dạng base64 trong secrets)
      - name: Decode Google Credentials
        run: echo "${{ secrets.GOOGLE_CREDENTIALS }}" | base64 -d > credentials.json

      - name: Run Update Post Title
        env:
          SITE_URL: ${{ secrets.SITE_URL }}
          CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
          SPREADSHEET_URL: ${{ secrets.SPREADSHEET_URL }}
        run: python postmkcom.py
