name: Update Post Title

on:
  schedule:
    - cron: '*/60 * * * *'
  workflow_dispatch:

jobs:
  update-post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests beautifulsoup4 gspread oauth2client

      - name: Run Update Post Title
        env:
          GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: python postmkcom.py
